### ISSUE TITLE
Bug with checkAccess

### ISSUE THREAD

**Issue by jundl77** [intellimate/izou-pf4j#17]
@LeanderK Try to start Izou with this new version of pf4j as a module dependency instead of the maven dependency. At least for me, Izou does not start because of this method, the LinkageError below is throw for the `ro.fortsoft.pf4j.Plugin` class.

Do you also have this problem?

Here is the method in the IzouPluginClassLoader class.

``` java
/**
 * checks whether the Addon is allowed to access the class
 * @param parentResult the resulting class
 * @return the Class or an Exception
 */
private Class<?> checkAccess(Class<?> parentResult, String classname) throws LinkageError {
    if (parentResult.isAnnotationPresent(AddonAccessible.class) && parentResult.isInterface()) {
        return parentResult;
    } else {
        throw new LinkageError("Requested class: " + classname + " is not accessible for addons");
    }
}
```

**Comment by LeanderK** [comment]
well...do you want to access a class you re not allowed to access? this is my code to prevent addons from accessing classes from izou (and performing reflection on it)

**Comment by LeanderK** [comment]
i think the code explains itself, do you have questions?

**Comment by jundl77** [comment]
yes yes, but for me izou crashes with that (it did not before I made my changes, with that code still there)
I am just not sure why

**Comment by LeanderK** [comment]
well, did you debug it? maybe a small code changes slipped through and an forbidden class is requested

**Comment by jundl77** [comment]
Ok so yes I did debug it and it is clearly the class ro.fortsoft.pf4j.Plugin, and when I put the @AddOnAccessible annotation before the class, then it still does not work. Perhaps because it's not an interface?

**Comment by jundl77** [comment]
Yes lol, why does it say && parentResult.isInterface() ? Does it have to be an interface?
